pipeline {
    agent { label 'ubuntu-agent'}

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/hridyen/microservices-ci.git'
            }
        }

        stage('Check Changes') {
            when {
                not {
                    changeset "login-service/**"
                }
            }
            steps {
                echo "No changes in login-service. Skipping..."
                script { currentBuild.result = 'NOT_BUILT' }
            }
        }

        stage('Build Docker Image') {
            when {
                changeset "login-service/**"
            }
            steps {
                echo "Building LOGIN service..."
                sh '''
                cd login-service
                docker build -t login-service .
                '''
            }
        }

        stage('Run Container') {
            when {
                changeset "login-service/**"
            }
            steps {
                echo "Running LOGIN container..."
                sh '''
                docker rm -f login-container || true
                docker run -d -p 3003:3003 --name login-container login-service
                '''
            }
        }
    }

    post {
        success {
            echo "Login Service Done 🚀"
        }
    }
}