pipeline {
    agent { label 'ubuntu-agent'}

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/hridyen/microservices-ci.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "Building CONFIG service..."
                sh '''
                cd config-service
                docker build -t config-service .
                '''
            }
        }

        stage('Run Container') {
            steps {
                echo "Running CONFIG container..."
                sh '''
                docker rm -f config-container || true
                docker run -d -p 3002:3002 --name config-container config-service
                '''
            }
        }
    }

    post {
        success {
            echo "Config Service Deployed "
        }
        failure {
            echo "Config Service Failed "
        }
    }
}