pipeline {
    agent { label 'ubuntu-agent'}

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/hridyen/microservices-ci.git'
            }
        }

        stage('Check Changes') {
            when {
                not {
                    changeset "config-service/**"
                }
            }
            steps {
                echo "No changes in config-service. Skipping..."
                script { currentBuild.result = 'NOT_BUILT' }
            }
        }

        stage('Build Docker Image') {
            when {
                changeset "config-service/**"
            }
            steps {
                echo "Building CONFIG service..."
                sh '''
                cd config-service
                docker build -t config-service .
                '''
            }
        }

        stage('Run Container') {
            when {
                changeset "config-service/**"
            }
            steps {
                echo "Running CONFIG container..."
                sh '''
                docker rm -f config-container || true
                docker run -d -p 3002:3002 --name config-container config-service
                '''
            }
        }
    }

    post {
        success {
            echo "Config Service Done 🚀"
        }
    }
}