pipeline {
    agent { label 'ubuntu-agent'}

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/hridyen/microservices-ci.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "Building AUTH service..."
                sh '''
                cd auth-service
                docker build -t auth-service .
                '''
            }
        }

        stage('Run Container') {
            steps {
                echo "Running AUTH container..."
                sh '''
                docker rm -f auth-container || true
                docker run -d -p 3001:3001 --name auth-container auth-service
                '''
            }
        }
    }

    post {
        success {
            echo "Auth Service Deployed "
        }
        failure {
            echo "Auth Service Failed "
        }
    }
}