pipeline {
    agent { label 'ubuntu-agent'}

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/hridyen/microservices-ci.git'
            }
        }

        stage('Check Changes') {
            when {
                not {
                    changeset "auth-service/**"
                }
            }
            steps {
                echo "No changes in auth-service. Skipping..."
                script { currentBuild.result = 'NOT_BUILT' }
            }
        }

        stage('Build Docker Image') {
            when {
                changeset "auth-service/**"
            }
            steps {
                echo "Building AUTH service..."
                sh '''
                cd auth-service
                docker build -t auth-service .
                '''
            }
        }

        stage('Run Container') {
            when {
                changeset "auth-service/**"
            }
            steps {
                echo "Running AUTH container..."
                sh '''
                docker rm -f auth-container || true
                docker run -d -p 3001:3001 --name auth-container auth-service
                '''
            }
        }
    }

    post {
        success {
            echo "Auth Service Done 🚀"
        }
    }
}